"""add funding programs and guideline documents

Revision ID: 473569007f0d
Revises: 91aea7abba7c
Create Date: 2026-02-07 15:00:40.428944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '473569007f0d'
down_revision: Union[str, Sequence[str], None] = '91aea7abba7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('template_source', sa.String(), nullable=False),
    sa.Column('template_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_programs_id'), 'funding_programs', ['id'], unique=False)
    op.create_index(op.f('ix_funding_programs_title'), 'funding_programs', ['title'], unique=False)
    op.create_table('funding_program_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funding_program_id', sa.Integer(), nullable=False),
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['funding_program_id'], ['funding_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_program_documents_file_id'), 'funding_program_documents', ['file_id'], unique=False)
    op.create_index(op.f('ix_funding_program_documents_funding_program_id'), 'funding_program_documents', ['funding_program_id'], unique=False)
    op.create_index(op.f('ix_funding_program_documents_id'), 'funding_program_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_program_documents_id'), table_name='funding_program_documents')
    op.drop_index(op.f('ix_funding_program_documents_funding_program_id'), table_name='funding_program_documents')
    op.drop_index(op.f('ix_funding_program_documents_file_id'), table_name='funding_program_documents')
    op.drop_table('funding_program_documents')
    op.drop_index(op.f('ix_funding_programs_title'), table_name='funding_programs')
    op.drop_index(op.f('ix_funding_programs_id'), table_name='funding_programs')
    op.drop_table('funding_programs')
    # ### end Alembic commands ###
