"""add user_templates table

Revision ID: 7d822b08ffaa
Revises: f3eb6e9c6b35
Create Date: 2026-02-08 16:21:12.052685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d822b08ffaa'
down_revision: Union[str, Sequence[str], None] = 'f3eb6e9c6b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_templates_name'), 'user_templates', ['name'], unique=False)
    op.create_index(op.f('ix_user_templates_user_email'), 'user_templates', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_templates_user_email'), table_name='user_templates')
    op.drop_index(op.f('ix_user_templates_name'), table_name='user_templates')
    op.drop_table('user_templates')
    # ### end Alembic commands ###
